const palette=['#d9f0ec','#f7d7cd','#e4e0fa','#f6e6bb','#d8e6fb'];
const seedData={employees:[{id:'jordan',name:'Jordan Lee',role:'Product Designer',cadence:'weekly',next:'2026-08-25',color:0},{id:'maya',name:'Maya Chen',role:'Software Engineer',cadence:'biweekly',next:'2026-08-27',color:1},{id:'elena',name:'Elena Ruiz',role:'Customer Success',cadence:'weekly',next:'2026-08-31',color:2},{id:'sam',name:'Sam Wright',role:'Data Analyst',cadence:'biweekly',next:'2026-09-02',color:3}],sessions:[{id:'s1',employeeId:'jordan',date:'2026-08-18',notes:'Reviewed the onboarding flow research. Jordan is excited to test a simpler first-run experience with the new cohort.'},{id:'s2',employeeId:'maya',date:'2026-08-13',notes:'Talked through the API migration plan and where Maya would like more support from the platform team.'},{id:'s3',employeeId:'elena',date:'2026-08-24',notes:'Celebrated a strong renewal month. Discussed setting clearer expectations with two newer accounts.'}],actions:[{id:'a1',employeeId:'jordan',text:'Share first-run research plan with the team',owner:'employee',due:'2026-08-25',done:false,createdAt:null},{id:'a2',employeeId:'maya',text:'Connect Maya with the platform API owner',owner:'manager',due:'2026-08-27',done:false,createdAt:null},{id:'a3',employeeId:'elena',text:'Draft a template for account expectation setting',owner:'employee',due:'2026-08-31',done:false,createdAt:null},{id:'a4',employeeId:'sam',text:'Review Q3 dashboard priorities',owner:'employee',due:'2026-08-20',done:true,createdAt:null}],discussionPoints:[]};
let data=structuredClone(seedData),fileHandle,currentEmployee=null,actionFilter='open',activeSessionId=null,activeSessionActionId=null,activeSessionEmployeeId=null;
const handleDatabaseName='one-on-one-file-handle',handleStoreName='handles',handleKey='workspace-file';
const sessionDraftKey='one-on-one-session-draft';let sessionDraftTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],id=p=>`${p}${crypto.randomUUID()}`;
const emp=id=>data.employees.find(x=>x.id===id),initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}),fullDate=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
const avatar=e=>`<span class="avatar" style="background:${palette[e.color%palette.length]}">${initials(e.name)}</span>`;
function normal(value){if(!value||typeof value!=='object')throw Error('This is not an Edwards Experience data file.');return {employees:Array.isArray(value.employees)?value.employees:[],sessions:Array.isArray(value.sessions)?value.sessions:[],actions:Array.isArray(value.actions)?value.actions.map(({createdAt,...action})=>action):[],discussionPoints:Array.isArray(value.discussionPoints)?value.discussionPoints:[]}}
function cleanRichText(value){const template=document.createElement('template'),allowed=new Set(['A','B','STRONG','I','EM','U','S','STRIKE','DEL','P','DIV','BR','UL','OL','LI','BLOCKQUOTE']);template.innerHTML=value||'';const clean=node=>{[...node.children].forEach(child=>{clean(child);if(!allowed.has(child.tagName)){child.replaceWith(...child.childNodes);return}if(child.tagName==='A'){const href=child.getAttribute('href')||'';if(!/^(https?:|mailto:)/i.test(href))child.removeAttribute('href');else{child.setAttribute('target','_blank');child.setAttribute('rel','noopener noreferrer')}}[...child.attributes].forEach(attribute=>{if(child.tagName!=='A'||!['href','target','rel'].includes(attribute.name))child.removeAttribute(attribute.name)})})};clean(template.content);return template.innerHTML}
function notesHtml(notes){const text=String(notes||'');return cleanRichText(text.includes('<')?text:text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>'))}
function handleDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open(handleDatabaseName,1);request.onupgradeneeded=()=>request.result.createObjectStore(handleStoreName);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function savedHandle(){const db=await handleDatabase();return new Promise((resolve,reject)=>{const request=db.transaction(handleStoreName).objectStore(handleStoreName).get(handleKey);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function rememberHandle(handle){const db=await handleDatabase();return new Promise((resolve,reject)=>{const request=db.transaction(handleStoreName,'readwrite').objectStore(handleStoreName).put(handle,handleKey);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
async function hasFilePermission(handle){return (await handle.queryPermission({mode:'readwrite'}))==='granted'}
function offerReconnect(message='The saved workspace file needs permission before it can be updated.'){if(fileHandle){$('#fileDialogTitle').textContent='Reconnect your workspace';$('#fileDialogMessage').textContent=message;$('#reconnectFileButton').classList.remove('hidden')}$('#fileDialog').showModal()}
async function loadHandle(handle){data=normal(JSON.parse(await (await handle.getFile()).text()));fileHandle=handle;renderAll();applyRoute();$('#fileStatus').textContent=`Using ${fileHandle.name}`}
async function save(){if(!fileHandle)throw Error('Choose a data file before making changes.');if(!await hasFilePermission(fileHandle)){offerReconnect();throw Error('Reconnect the saved workspace file before making changes.')}try{const writer=await fileHandle.createWritable();await writer.write(JSON.stringify(data,null,2));await writer.close();$('#fileStatus').textContent=`Saving to ${fileHandle.name}`}catch(e){if(e.name==='NotAllowedError'){offerReconnect('Your browser blocked write access to the saved file. Reconnect it, then try your change again.');throw Error('Reconnect the saved workspace file before making changes.')}throw e}}
async function change(mutator){mutator();await save();renderAll()}
async function openFile(){try{[fileHandle]=await showOpenFilePicker({multiple:false,types:[{description:'The Edwards Experience data',accept:{'application/json':['.json']}}]});if(!await hasFilePermission(fileHandle)&&await fileHandle.requestPermission({mode:'readwrite'})!=='granted')throw Error('Write permission was not granted for this file.');await rememberHandle(fileHandle);await loadHandle(fileHandle);$('#fileDialog').close()}catch(e){if(e.name!=='AbortError')alert(`Could not open this file: ${e.message}`)}}
async function createFile(){try{fileHandle=await showSaveFilePicker({suggestedName:'edwards-experience-data.json',types:[{description:'The Edwards Experience data',accept:{'application/json':['.json']}}]});if(!await hasFilePermission(fileHandle)&&await fileHandle.requestPermission({mode:'readwrite'})!=='granted')throw Error('Write permission was not granted for this file.');await rememberHandle(fileHandle);data=structuredClone(seedData);await save();$('#fileDialog').close();renderAll();$('#fileStatus').textContent=`Using ${fileHandle.name}`}catch(e){if(e.name!=='AbortError')alert(`Could not create the file: ${e.message}`)}}
const routePaths={overview:'#/',employees:'#/people',agenda:'#/agenda',actions:'#/actions'};
function routeForView(view){return view==='employee'&&currentEmployee?`#/people/${encodeURIComponent(currentEmployee)}`:routePaths[view]||routePaths.overview}
function showView(view,updateUrl=true){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(updateUrl&&location.hash!==routeForView(view))location.hash=routeForView(view)}
function applyRoute(){const route=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);if(route[0]==='people'&&route[1]){const employeeId=decodeURIComponent(route[1]);if(emp(employeeId)){openEmployee(employeeId,false);return}}const view=route[0]==='people'?'employees':route[0]==='agenda'?'agenda':route[0]==='actions'?'actions':'overview';currentEmployee=null;showView(view,false)}
function actionRows(items){return items.map(a=>{const e=emp(a.employeeId);return `<div class="action-row"><input class="check" type="checkbox" data-action="${a.id}" ${a.done?'checked':''}><div class="action-copy"><strong>${a.text}</strong><small>${e?.name||'Former employee'} · ${a.owner==='manager'?'You own this':'They own this'}</small></div>${a.due?`<span class="due">${a.done?'DONE':dateLabel(a.due)}</span>`:''}</div>`}).join('')}
function bindChecks(){$$('.check').forEach(c=>c.onchange=async()=>{try{await change(()=>data.actions.find(a=>a.id===c.dataset.action).done=c.checked)}catch(e){alert(e.message);renderAll()}})}
function discussionRows(points,shared=false){return points.map(p=>`<div class="action-row"><input class="check discussion-check" type="checkbox" data-point="${p.id}" ${p.done?'checked':''}><div class="action-copy"><strong>${p.text}</strong><small>${shared?'Shared with every employee':'Discussion point'}</small></div><span class="agenda-tag">${p.done?'DISCUSSED':'AGENDA'}</span></div>`).join('')}
function bindDiscussionChecks(){$$('.discussion-check').forEach(c=>c.onchange=async()=>{try{await change(()=>data.discussionPoints.find(p=>p.id===c.dataset.point).done=c.checked)}catch(e){alert(e.message);renderAll()}})}
function renderSessionAgenda(employeeId){const points=data.discussionPoints.filter(p=>p.employeeId===employeeId&&!p.done),list=$('#sessionAgendaItems');list.innerHTML=points.length?points.map(p=>`<label class="session-agenda-item"><input class="check session-agenda-check" type="checkbox" data-point="${p.id}"><span>${p.text}${p.sharedGroup?' · Team-wide':''}</span></label>`).join(''):'<p class="session-agenda-empty">No open agenda items.</p>';$$('.session-agenda-check').forEach(check=>check.onchange=async()=>{try{await change(()=>data.discussionPoints.find(p=>p.id===check.dataset.point).done=check.checked);renderSessionAgenda(employeeId)}catch(e){alert(e.message);renderSessionAgenda(employeeId)}})}
function renderSessionActions(employeeId){const actions=data.actions.filter(a=>a.employeeId===employeeId&&a.done!==true).sort((a,b)=>(a.due||'9999-12-31').localeCompare(b.due||'9999-12-31')),list=$('#sessionActionItems');list.innerHTML=actions.length?actions.map(a=>`<label class="session-action-item"><input class="check session-action-check" type="checkbox" data-action="${a.id}" aria-label="Mark ${a.text} as complete"><span class="session-action-copy"><strong>${a.text}</strong><small>${a.owner==='manager'?'You own this':'They own this'}${a.due?` · Due ${dateLabel(a.due)}`:''}</small></span></label>`).join(''):'<p class="session-agenda-empty">No incomplete action items.</p>';$$('.session-action-check').forEach(check=>check.onchange=async()=>{try{await change(()=>data.actions.find(a=>a.id===check.dataset.action).done=check.checked);renderSessionActions(employeeId)}catch(e){alert(e.message);renderSessionActions(employeeId)}})}
function renderSidebar(){$('#teamList').innerHTML=data.employees.map(e=>`<button class="team-member" data-person="${e.id}">${avatar(e)}<span>${e.name}</span></button>`).join('');$('#actionCount').textContent=data.actions.filter(a=>!a.done).length;$('#agendaCount').textContent=new Set(data.discussionPoints.filter(p=>p.sharedGroup&&!p.done).map(p=>p.sharedGroup)).size;$$('.team-member').forEach(b=>b.onclick=()=>openEmployee(b.dataset.person))}
function renderOverview(){$('#todayLabel').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('#upcomingList').innerHTML=[...data.employees].sort((a,b)=>a.next.localeCompare(b.next)).slice(0,4).map(e=>{const d=new Date(e.next+'T12:00:00');return `<button class="meeting-card" type="button" data-person="${e.id}" aria-label="Open ${e.name}'s 1:1"><div class="date-box"><b>${d.getDate()}</b><span>${d.toLocaleString('en-US',{month:'short'})}</span></div>${avatar(e)}<div class="meeting-info"><strong>${e.name}</strong><p>${e.role} · ${e.cadence==='weekly'?'Weekly':'Every other week'}</p></div><span class="status-tag">OPEN 1:1 →</span></button>`}).join('')||'<p class="empty">Add a team member to get started.</p>';$('#overviewActions').innerHTML=actionRows(data.actions.filter(a=>!a.done).slice(0,4))||'<p class="empty">No open action items.</p>';$$('.meeting-card').forEach(c=>c.onclick=()=>openEmployee(c.dataset.person));bindChecks()}
function renderPeople(){$('#peopleGrid').innerHTML=data.employees.map(e=>{const n=data.actions.filter(a=>a.employeeId===e.id&&!a.done).length;return `<article class="person-card" data-person="${e.id}"><div class="person-card-top">${avatar(e)}<span class="cadence">${e.cadence==='weekly'?'WEEKLY':'BIWEEKLY'}</span></div><h3>${e.name}</h3><p>${e.role||'Team member'}</p><div class="person-card-footer"><span>Next: ${dateLabel(e.next)}</span><span>${n} open ${n===1?'item':'items'}</span></div></article>`}).join('')||'<p class="empty">Your team is empty. Add your first employee.</p>';$$('.person-card').forEach(c=>c.onclick=()=>openEmployee(c.dataset.person))}
function renderActions(){const items=data.actions.filter(a=>actionFilter==='all'||(actionFilter==='open'?!a.done:a.done));$('#actionsList').innerHTML=actionRows(items)||'<p class="empty">Nothing here yet.</p>';bindChecks()}
function renderTeamAgenda(){const groups=Object.values(data.discussionPoints.filter(p=>p.sharedGroup).reduce((all,p)=>{(all[p.sharedGroup]??=[]).push(p);return all},{})),teamIds=new Set(data.employees.map(e=>e.id));$('#teamAgendaList').innerHTML=groups.map(points=>{const teamPoints=points.filter(p=>teamIds.has(p.employeeId)),discussed=teamPoints.filter(p=>p.done).length,complete=teamIds.size>0&&teamPoints.length===teamIds.size&&discussed===teamIds.size;return `<div class="action-row team-agenda-row ${complete?'team-agenda-row--complete':''}"><div class="action-copy"><strong>${points[0].text}</strong><small>${complete?'Completed by everyone':`${discussed} of ${teamIds.size} employees discussed this`}</small></div><span class="agenda-tag ${complete?'agenda-tag--complete':''}">${complete?'✓ COMPLETE':'TEAM-WIDE'}</span></div>`}).join('')||'<p class="empty">No shared discussion points yet.</p>'}
function openEmployee(employeeId){currentEmployee=employeeId;const e=emp(employeeId);showView('employee');$('#employeeHeader').innerHTML=`<div class="employee-identity">${avatar(e)}<div><p class="eyebrow">TEAM MEMBER</p><h1>${e.name}</h1><p class="employee-role">${e.role||'Team member'} <span aria-hidden="true">•</span> ${e.cadence==='weekly'?'Weekly 1:1':'Every other week 1:1'}</p></div></div><div class="header-actions"><div class="next-meeting"><span class="eyebrow">NEXT 1:1</span><strong>${fullDate(e.next)}</strong></div><button class="primary-button employee-log-session" id="employeeLogSessionButton">+ Log a 1:1</button><div class="employee-management"><button class="edit-employee" id="editEmployeeButton">Edit employee</button><button class="delete-employee" id="deleteEmployeeButton">Delete employee</button></div></div>`;$('#employeeLogSessionButton').onclick=openSession;$('#editEmployeeButton').onclick=()=>openEditEmployee(e);$('#deleteEmployeeButton').onclick=()=>deleteEmployee(e);renderEmployeeContent()}
function openEditEmployee(employee){const form=$('#editEmployeeForm');form.elements.name.value=employee.name;form.elements.role.value=employee.role||'';form.elements.cadence.value=employee.cadence;form.elements.next.value=employee.next;$('#editEmployeeDialog').showModal()}
async function deleteEmployee(person){if(!confirm(`Delete ${person.name} and all of their 1:1 notes and action items? This cannot be undone.`))return;try{await change(()=>{data.employees=data.employees.filter(e=>e.id!==person.id);data.sessions=data.sessions.filter(s=>s.employeeId!==person.id);data.actions=data.actions.filter(a=>a.employeeId!==person.id);data.discussionPoints=data.discussionPoints.filter(p=>p.employeeId!==person.id)});currentEmployee=null;showView('employees')}catch(e){alert(e.message)}}
function renderEmployeeContent(){const sessions=data.sessions.filter(s=>s.employeeId===currentEmployee).sort((a,b)=>b.date.localeCompare(a.date)),actions=data.actions.filter(a=>a.employeeId===currentEmployee),team=data.discussionPoints.filter(p=>p.employeeId===currentEmployee&&p.sharedGroup),personal=data.discussionPoints.filter(p=>p.employeeId===currentEmployee&&!p.sharedGroup);$('#notesPanel').innerHTML=sessions.length?`<div class="history-summary"><div><p class="eyebrow">CONVERSATION HISTORY</p><h2>${sessions.length} documented ${sessions.length===1?'conversation':'conversations'}</h2></div><span>Most recent first</span></div><div class="session-list">${sessions.map(s=>`<article class="session-card"><div class="session-meta"><div><p class="eyebrow">1:1 CONVERSATION</p><strong>Meeting notes</strong></div><time datetime="${s.date}">${fullDate(s.date)}</time></div><div class="session-notes">${notesHtml(s.notes)}</div><div class="session-footer"><button class="text-button delete-session" data-session="${s.id}">Delete 1:1</button><button class="text-button edit-session" data-session="${s.id}">Edit notes <span aria-hidden="true">→</span></button></div></article>`).join('')}</div>`:'<p class="empty">No conversations documented yet. Log your next 1:1 to begin.</p>';$$('.edit-session').forEach(button=>button.onclick=()=>openSession(button.dataset.session));$$('.delete-session').forEach(button=>button.onclick=()=>deleteSession(button.dataset.session));$('#employeeAgendaPanel').innerHTML=`<button class="secondary-button add-agenda-button" id="addEmployeePointButton">+ Add discussion point</button>${team.length?`<p class="agenda-heading">TEAM-WIDE</p>${discussionRows(team,true)}`:''}${personal.length?`<p class="agenda-heading">FOR THIS 1:1</p>${discussionRows(personal)}`:''}${!team.length&&!personal.length?'<p class="empty">No discussion points yet.</p>':''}`;$('#addEmployeePointButton').onclick=()=>openDiscussionDialog(currentEmployee);$('#employeeActionsPanel').innerHTML=actionRows(actions)||'<p class="empty">No action items for this person.</p>';bindChecks();bindDiscussionChecks()}
async function deleteSession(sessionId){if(!confirm('Delete this 1:1 and its notes? This cannot be undone. Action items will be kept.'))return;try{await change(()=>{data.sessions=data.sessions.filter(s=>s.id!==sessionId)})}catch(e){alert(e.message)}}
function renderAll(){renderSidebar();renderOverview();renderPeople();renderActions();renderTeamAgenda();if(currentEmployee&&emp(currentEmployee))renderEmployeeContent()}
function sessionDraft(){const form=$('#sessionForm');return {employeeId:form.employeeId.value,date:form.date.value,notes:$('#sessionNotes').innerHTML,addAction:$('#addActionToggle').checked,actionText:form.actionText.value,owner:form.owner.value,dueDate:form.dueDate.value}}
async function saveSessionDraft(){clearTimeout(sessionDraftTimer);const draft=sessionDraft(),hasNote=$('#sessionNotes').innerText.trim(),hasAction=draft.addAction&&draft.actionText.trim();if(!hasNote&&!hasAction)return;try{await change(()=>{let session=data.sessions.find(s=>s.id===activeSessionId),isNew=false;if(!session){activeSessionId=id('s');session={id:activeSessionId};data.sessions.push(session);isNew=true}Object.assign(session,{employeeId:draft.employeeId,date:draft.date,notes:cleanRichText(draft.notes),inProgress:false});if(isNew){const next=new Date(`${draft.date}T12:00:00`),employee=emp(draft.employeeId);next.setDate(next.getDate()+(employee.cadence==='weekly'?7:14));employee.next=next.toISOString().slice(0,10)}if(hasAction){let action=data.actions.find(a=>a.id===activeSessionActionId);if(action)Object.assign(action,{employeeId:draft.employeeId,text:draft.actionText.trim(),owner:draft.owner,due:draft.dueDate||null});else{activeSessionActionId=id('a');data.actions.push({id:activeSessionActionId,employeeId:draft.employeeId,text:draft.actionText.trim(),owner:draft.owner,due:draft.dueDate||null,done:false})}}});localStorage.removeItem(sessionDraftKey);renderSessionActions(draft.employeeId);$('#sessionDraftStatus').textContent='Saved automatically'}catch(e){try{localStorage.setItem(sessionDraftKey,JSON.stringify(draft))}catch(_){}console.warn('Unable to save 1:1',e);$('#sessionDraftStatus').textContent='Could not save—your local backup is retained'}}
function queueSessionDraft(){clearTimeout(sessionDraftTimer);$('#sessionDraftStatus').textContent='Saving to this 1:1…';sessionDraftTimer=setTimeout(saveSessionDraft,500)}
function clearSessionDraft(){clearTimeout(sessionDraftTimer);localStorage.removeItem(sessionDraftKey);$('#sessionDraftStatus').textContent=''}
function openSession(sessionId=''){if(!data.employees.length)return alert('Add an employee before logging a 1:1.');const session=data.sessions.find(s=>s.id===sessionId);if(session)return openSessionEntry(session.employeeId,session);const picker=$('#sessionEmployeePicker');picker.innerHTML=data.employees.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');let defaultEmployee=currentEmployee||data.employees[0].id;try{const backup=JSON.parse(localStorage.getItem(sessionDraftKey)||'null');if(emp(backup?.employeeId))defaultEmployee=backup.employeeId}catch(e){console.warn('Unable to read 1:1 backup',e)}picker.value=defaultEmployee;$('#sessionPersonDialog').showModal()}
function openSessionEntry(employeeId,session=null){const form=$('#sessionForm'),person=emp(employeeId);activeSessionId=session?.id||null;activeSessionActionId=null;activeSessionEmployeeId=employeeId;form.reset();form.employeeId.value=employeeId;$('#sessionPersonLabel').textContent=`1:1 with ${person.name}`;renderSessionAgenda(employeeId);renderSessionActions(employeeId);form.date.value=session?.date||new Date().toISOString().slice(0,10);$('#sessionNotes').innerHTML=session?notesHtml(session.notes):'';$('#newActionFields').classList.add('hidden');$('#sessionDraftStatus').textContent=session?'Editing saved 1:1':'';if(!session)try{const draft=JSON.parse(localStorage.getItem(sessionDraftKey)||'null');if(draft&&draft.employeeId===employeeId){form.date.value=draft.date||form.date.value;$('#sessionNotes').innerHTML=cleanRichText(draft.notes);$('#addActionToggle').checked=Boolean(draft.addAction);form.actionText.value=draft.actionText||'';form.owner.value=draft.owner||'employee';form.dueDate.value=draft.dueDate||'';$('#newActionFields').classList.toggle('hidden',!draft.addAction);$('#sessionDraftStatus').textContent='Restoring unsaved backup';queueSessionDraft()}}catch(e){console.warn('Unable to restore 1:1 backup',e)}showView('session',false)}
async function closeSession(){await saveSessionDraft();if(activeSessionEmployeeId&&emp(activeSessionEmployeeId))openEmployee(activeSessionEmployeeId);else showView('overview')}
function openDiscussionDialog(employeeId=''){$('#discussionEmployeeId').value=employeeId;$('#discussionScopeLabel').textContent=employeeId?'1:1 AGENDA':'TEAM AGENDA';$('#discussionDialog').showModal()}
const emojiList='😀 😃 😄 😁 😆 🥹 😊 😇 🙂 🙃 😉 😍 🥳 🤔 🤗 🤝 👍 👎 👏 🙌 💪 👀 ✅ ✨ 🎉 🚀 💡 📌 📈 🧠 ❤️ 💚 💙 💛 🔥 ☕ 🌱 🗓️ ⏰ 📝 💬 🎯 ⚠️ ❓ ⭐ 🏆 🎁 🌟 😕 😟 😮 😢 😤 😅 😂 🙏 🤞 💯'.split(' ');
const richToolbar=$('.rich-toolbar'),strikeButton=document.createElement('button'),emojiButton=document.createElement('button'),emojiPanel=document.createElement('div');richToolbar.querySelectorAll('button[data-emoji]').forEach(button=>button.remove());strikeButton.type='button';strikeButton.dataset.command='strikeThrough';strikeButton.title='Strikethrough';strikeButton.innerHTML='<s>S</s>';emojiButton.type='button';emojiButton.dataset.command='emoji-menu';emojiButton.title='More emojis';emojiButton.textContent='☺+';emojiPanel.className='emoji-panel hidden';emojiList.forEach(emoji=>{const button=document.createElement('button');button.type='button';button.dataset.emoji=emoji;button.textContent=emoji;button.title=`Insert ${emoji}`;emojiPanel.append(button)});richToolbar.insertBefore(strikeButton,richToolbar.querySelector('span'));richToolbar.append(emojiButton);richToolbar.parentElement.append(emojiPanel);
$('#openFileButton').onclick=openFile;$('#createFileButton').onclick=createFile;$('#reconnectFileButton').onclick=async()=>{try{const permission=await fileHandle.requestPermission({mode:'readwrite'});if(permission==='granted'){await loadHandle(fileHandle);$('#fileDialog').close()}else alert('Permission was not granted.')}catch(e){alert(`Could not reconnect the saved file: ${e.message}`)}};$('#changeFileButton').onclick=()=>$('#fileDialog').showModal();$('#peopleAddButton').onclick=()=>$('#employeeDialog').showModal();$('#quickSessionButton').onclick=openSession;$('#backToPeople').onclick=()=>showView('employees');$('#closeSessionButton').onclick=closeSession;$$('.close-modal').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#addActionToggle').onchange=e=>{$('#newActionFields').classList.toggle('hidden',!e.target.checked);queueSessionDraft()};
$('#addTeamPointButton').onclick=()=>openDiscussionDialog();
window.addEventListener('hashchange',applyRoute);
$('#sessionPersonForm').addEventListener('submit',e=>{e.preventDefault();const employeeId=$('#sessionEmployeePicker').value;$('#sessionPersonDialog').close();openSessionEntry(employeeId)});
function applyEditorCommand(command,value=null){const editor=$('#sessionNotes');editor.focus();document.execCommand(command,false,value);queueSessionDraft()}
$$('.rich-toolbar button').forEach(button=>{button.onmousedown=event=>event.preventDefault();button.onclick=()=>{const command=button.dataset.command,emoji=button.dataset.emoji;if(emoji)return applyEditorCommand('insertText',emoji);if(command==='emoji-menu'){emojiPanel.classList.toggle('hidden');return}if(command==='link'){const url=prompt('Paste a link (https://...)');if(url)applyEditorCommand('createLink',url);return}applyEditorCommand(command)}});
$$('.emoji-panel button').forEach(button=>{button.onmousedown=event=>event.preventDefault();button.onclick=()=>{applyEditorCommand('insertText',button.dataset.emoji);emojiPanel.classList.add('hidden')}});
$$('.employee-tab').forEach(tab=>tab.onclick=()=>{const selected=tab.dataset.tab;$$('.employee-tab').forEach(i=>i.classList.toggle('active',i===tab));$('#notesPanel').classList.toggle('hidden',selected!=='notes');$('#employeeAgendaPanel').classList.toggle('hidden',selected!=='agenda');$('#employeeActionsPanel').classList.toggle('hidden',selected!=='employee-actions')});
$('#sessionNotes').addEventListener('input',queueSessionDraft);$('#sessionForm').addEventListener('input',queueSessionDraft);$('#sessionForm').addEventListener('change',queueSessionDraft);
window.addEventListener('pagehide',()=>{if($('#sessionView').classList.contains('active')){try{localStorage.setItem(sessionDraftKey,JSON.stringify(sessionDraft()))}catch(_){}saveSessionDraft()}});
$('#employeeForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await change(()=>data.employees.push({id:id('e'),name:f.get('name').trim(),role:f.get('role').trim(),cadence:f.get('cadence'),next:new Date().toISOString().slice(0,10),color:data.employees.length%palette.length}));e.target.reset();$('#employeeDialog').close()}catch(e){alert(e.message)}});
$('#editEmployeeForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),employee=emp(currentEmployee);if(!employee)return;try{await change(()=>Object.assign(employee,{name:f.get('name').trim(),role:f.get('role').trim(),cadence:f.get('cadence'),next:f.get('next')}));$('#editEmployeeDialog').close();openEmployee(employee.id)}catch(e){alert(e.message)}});
$('#sessionForm').addEventListener('submit',e=>e.preventDefault());
$('#discussionForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),text=f.get('text').trim(),employeeId=f.get('employeeId');try{await change(()=>{if(employeeId)data.discussionPoints.push({id:id('d'),employeeId,text,done:false});else{const group=id('g');data.employees.forEach(person=>data.discussionPoints.push({id:id('d'),employeeId:person.id,text,done:false,sharedGroup:group}))}});e.target.reset();$('#discussionDialog').close()}catch(e){alert(e.message)}});
$$('.filter').forEach(b=>b.onclick=()=>{actionFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderActions()});$('#resetButton').onclick=async()=>{if(confirm('Restore the sample workspace? All saved records in this JSON file will be replaced.'))try{currentEmployee=null;await change(()=>data=structuredClone(seedData));showView('overview')}catch(e){alert(e.message)}};
async function restoreWorkspace(){if(!window.showOpenFilePicker||!window.showSaveFilePicker||!window.indexedDB){$('#fileDialog').innerHTML='<div class="file-dialog-copy"><h2>Use Chrome or Edge</h2><p>This local-file version needs the File System Access API and IndexedDB, available in current Chrome and Edge browsers.</p></div>';return}try{const saved=await savedHandle();if(saved){fileHandle=saved;if(await hasFilePermission(saved)){await loadHandle(saved);return}offerReconnect(`${saved.name} is remembered. Reconnect it to continue without selecting the file again.`);return}}catch(e){console.warn('Unable to restore saved workspace file',e)}$('#fileDialog').showModal()}
applyRoute();
restoreWorkspace();
